name: Merge Upstream (upstream)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: 'upstream'
        token: ${{ secrets.GH_TOKEN_FOR_MERGE }} #Custom Token required to write workflow file

    - name: Fetch Upstream
      run: |
        git config --global user.email "66754887+Srgr0@users.noreply.github.com"
        git config --global user.name "Srgr0"
        git remote add upstream https://github.com/misskey-dev/misskey.git
        git fetch upstream develop

    - name: Merge Upstream
      run: |
        git merge upstream/develop --no-edit
        if [ $? -ne 0 ]; then
          echo "Merge conflict detected, stopping workflow."
          exit 1
        fi

    - name: Push Changes
      run: git push origin upstream

  trigger_docker-develop:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: 'Trigger Dispatch Event'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN_FOR_DISPATCH_dd }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/srgr0/misskey/actions/workflows/docker-develop.yml/dispatches \
               -d '{"ref": "default", "inputs": {"branch": "upstream"}}'
