name: Deploy test environment

on:
  #push
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'develop-srgr0'

    - name: Start ngrok tunnel
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok http -auth="${{ secrets.ACCESS_ID }}:${{ secrets.ACCESS_PASS }}" 3000 &

    - name: Install misskey
      run: |
        wget https://raw.githubusercontent.com/Srgr0/bash-install/refactor/a.sh
        wget https://raw.githubusercontent.com/Srgr0/bash-install/refactor/testenv_systemd.txt
        chmod +x a.sh
        ./a.sh -c testenv_systemd.txt

    - name: Wait
      run: |
        sleep 3600
