name: deploy-test-environment

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to deploy (optional, use the repository where this workflow is stored by default)'
        required: false
        default: ''
      branch_or_hash:
        description: 'Branch or Commit hash to deploy (optional, use the branch where this workflow is stored by default)'
        required: false
        default: ''
      wait_time:
        description: 'Time to wait in seconds (optional, 1800 seconds by default)'
        required: false
        default: ''

jobs:
  get-pr-ref:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/preview')
    outputs:
      is-allowed-user: ${{ steps.check-allowed-users.outputs.is-allowed-user }}
      pr-ref: ${{ steps.get-ref.outputs.pr-ref }}
      wait_time: ${{ steps.get-wait-time.outputs.wait_time }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check allowed users
        id: check-allowed-users
        run: |
          # 実行を許可するユーザーIDをカンマ区切りで入力, ユーザーIDは https://api.github.com/users/hogehoge で確認できます
          ALLOWED_USERS=""

          ALLOWED_USERS="$ALLOWED_USERS,20679825" # acid-chicken
          ALLOWED_USERS="$ALLOWED_USERS,22656849" # anatawa12
          ALLOWED_USERS="$ALLOWED_USERS,7106976" # EbiseLutica
          ALLOWED_USERS="$ALLOWED_USERS,67428053" # kakkokari-gtyih
          ALLOWED_USERS="$ALLOWED_USERS,63075513" # lunaisnotaboy
          ALLOWED_USERS="$ALLOWED_USERS,56515516" # mattyatea
          ALLOWED_USERS="$ALLOWED_USERS,46447427" # samunohito
          ALLOWED_USERS="$ALLOWED_USERS,3396686" # saschanaz
          ALLOWED_USERS="$ALLOWED_USERS,4439005" # syuilo
          ALLOWED_USERS="$ALLOWED_USERS,40626578" # tai-cha
          ALLOWED_USERS="$ALLOWED_USERS,7973572" # tamaina
          
          ALLOWED_USERS="$ALLOWED_USERS," # trailing comma
          COMMENT_AUTHOR="${{ github.event.comment.user.id }}"
          if [[ "$ALLOWED_USERS" == *",$COMMENT_AUTHOR,"* ]]; then
            echo "is-allowed-user=true" > $GITHUB_OUTPUT
          else
            echo "is-allowed-user=false" > $GITHUB_OUTPUT
          fi

      - name: Get PR ref
        id: get-ref
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)
          PR_REF=$(gh pr view $PR_NUMBER --json headRefName -q '.headRefName')
          echo "pr-ref=$PR_REF" > $GITHUB_OUTPUT

      - name: Extract wait time
        id: get-wait-time
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          WAIT_TIME=$(echo "$COMMENT_BODY" | grep -oP '(?<=/preview\s)\d+' || echo "1800")
          echo "wait_time=$WAIT_TIME" > $GITHUB_OUTPUT

  deploy-test-environment-pr-comment:
    needs: get-pr-ref
    if: needs.get-pr-ref.outputs.is-allowed-user == 'true'
    uses: joinmisskey/misskey-tga/.github/workflows/deploy-test-environment.yml@main
    with:
      repository: ${{ github.repository }}
      branch_or_hash: ${{ needs.get-pr-ref.outputs.pr-ref }}
      wait_time: ${{ needs.get-pr-ref.outputs.wait_time }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  deploy-test-environment-wd:
    if: github.event_name == 'workflow_dispatch'
    uses: joinmisskey/misskey-tga/.github/workflows/deploy-test-environment.yml@main
    with:
      repository: ${{ inputs.repository || github.repository }}
      branch_or_hash: ${{ inputs.branch_or_hash || github.ref_name }}
      wait_time: ${{ inputs.wait_time || '1800' }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
