#Dockle
#dockerイメージの脆弱性とかのチェック
#有効にしておく
---
name: Dockle

on:
  push:
    branches:
      - develop-srgr0
  pull_request:
    branches:
      - develop-srgr0
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issues:

jobs:
  dockle:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTENT_TRUST: 1
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v0.4.10/dockle_0.4.10_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
      - run: |
          cp .config/docker_example.env .config/docker.env
          cp ./docker-compose.yml.example ./docker-compose.yml
      - run: |
          docker compose up -d web
          docker tag "$(docker compose images web | awk 'OFS=":" {print $4}' | tail -n +2)" misskey-web:latest
      - run: |
          cmd="dockle --exit-code 1 misskey-web:latest ${image_name}"
          echo "> ${cmd}"
          eval "${cmd}"
