name: "Pull Request Labeler"
on:
#  pull_request_target:
#    branches-ignore:
#      - 'l10n_develop'
  push:
    branches:
      - four-zero-four

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
