# コード分析
#　有効にしておく
name: Lint

on:
  push:
    branches:
      - develop-srgr0
  pull_request:
    branches:
      - develop-srgr0
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issues:

jobs:
  pnpm_install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - uses: actions/setup-node@v3.8.1
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile

  lint:
    needs: [pnpm_install]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace:
        - backend
        - frontend
        - sw
        - misskey-js
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    - uses: actions/setup-node@v3.8.1
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: pnpm --filter ${{ matrix.workspace }} run eslint

  typecheck:
    needs: [pnpm_install]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace:
        - backend
        - misskey-js
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    - uses: actions/setup-node@v3.8.1
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: pnpm --filter ${{ matrix.workspace }} run typecheck
